lms/urls.py
import django
from lms.views import change_password
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/change_password/', views.change_password, name='change_password'),
    path('accounts/change_password_done/', views.change_password_done, name='change_password_done'),
    path('accounts/login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('accounts/register/', views.register, name='register'),
    path('accounts/register-as-teacher/', views.teacher_register, name='teacher_register'),
    path('accounts/register_done', views.register_done, name='register_done'),
    path('courses/add/', views.create_course, name='create_course'),
    path('courses/<int:course_id>/enroll/', views.course_enroll, name='enroll'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('courses/<int:course_id>/', views.course_overview, name='course_overview'),
    path('search/', views.search_result, name='search'),
    path('files/<str:file_path>', views.view_file, name='view_file'),
    path('<lect_id>/delete/', views.delete_lect, name='delete_lect'),
    path('courses/<int:course_id>/lectures/<lect_id>/modify/', views.modify_lect, name='modify_lect'),
    path('courses/<int:course_id>/add_lecture/', views.add_lecture, name='add_lecture'),
    path('courses/<int:course_id>/modify/', views.modify_course, name='modify_course'),
    path('courses/<int:course_id>/delete/', views.delete_course, name='delete_course'),
    path('courses/<int:course_id>/add_teacher/', views.add_teacher, name='add_teacher'),
    path('users/<int:user_id>', views.user_profile, name='user_profile'),
    path('db/', views.db_import, name='db_import'),
] + static('images', document_root=settings.IMAGE_DIR)

lms/forms.py
from django import forms
from django.contrib.admin import widgets
from django.contrib.auth.forms import UserCreationForm, ReadOnlyPasswordHashField
from django.contrib.auth.models import User
from django.contrib.admin.widgets import RelatedFieldWidgetWrapper
from django.forms.widgets import URLInput
from django.utils.translation import gettext_lazy as _
from .models import *


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', ]


class StudentInfoForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput, required=False)
    facebook = forms.URLField(widget=forms.URLInput, required=False)
    twitter = forms.URLField(widget=forms.URLInput, required=False)
    website = forms.URLField(widget=forms.URLInput, required=False)

    class Meta:
        model = Student
        fields = ['image', 'facebook', 'twitter', 'website', ]


class AddTeacherForm(forms.ModelForm):
    teacher = forms.ModelChoiceField(queryset=Teacher.objects.all())
    course = forms.ModelChoiceField(queryset=Course.objects.all())
    class Meta:
        model = Teach
        fields = ['teacher', 'course',]


'''class TeachForm(forms.ModelForm):
    teacher = forms.ModelChoiceField(queryset=Teacher.objects.all())
    course = forms.ModelChoiceField(queryset=Course.objects.all())

    class Meta:
        model = Teach
        fields = ['teacher', 'course',]'''


class TeacherInfoForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput, required=False, localize=True)
    facebook = forms.URLField(widget=forms.URLInput, required=False)
    twitter = forms.URLField(widget=forms.URLInput, required=False)
    website = forms.URLField(widget=forms.URLInput, required=False)

    class Meta:
        model = Teacher
        fields = ['image', 'facebook', 'twitter', 'website', ]


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        queryset = User.objects.filter(email=email)
        if queryset.exists():
            raise forms.ValidationError("Email existed")
        return email
    
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['name', ]


class TeacherRegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
    staff = forms.BooleanField(label='I agree to the Terms and Conditions.', initial=False)

    class Meta:
        model = User
        fields = ('email', 'password', 'password2', 'staff', )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        queryset = User.objects.filter(email=email)
        if queryset.exists():
            raise forms.ValidationError("Email existed")
        return email
    
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(TeacherRegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserAdminCreationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields, plus a repeated password.
    """
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class CourseCreateForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput, required=False)
    
    class Meta:
        model = Course
        fields = ['id', 'image', 'name', 'description', ]


class LectureCreateForm(forms.ModelForm):
    notes = forms.TextInput()
    slide = forms.FileField(widget=forms.FileInput, required=False)
    video = forms.URLField(widget=forms.URLInput, required=False)
    reading = forms.TextInput()

    class Meta:
        model = Lecture
        fields = ['course', 'name', 'notes', 'slide', 'video', 'reading', ]


class AssignmentCreateForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ['student', 'finished', ]


class EnrollmentForm(forms.ModelForm):
    class Meta:
        model = Enroll
        fields = ['student', 'course',]

lms/templates/courses/add_lecture.html
{% extends "../lms/index1.html" %}
{% block title %}Create Lecture{% endblock %}

{% block content %}
{% if lecture_create_form %}
<form method="POST" enctype='Multipart/form-data'>
    {% csrf_token %}
    <div class="box-bg-create-course">
        <div class="box-create-course">
            <h1>Create a new lecture</h1>
            <div class="label-fields-profile">
                <label for="id_course">Course</label>
                <label for="id_name">Name</label>
                <label for="id_slide">Slide</label>
                <label for="id_video">Video</label>
                <label for="id_notes">Notes</label>
            </div>

            <div class="inp-fields-profile" >
                <select name="course" required id="id_course">
                    <option value="{{ course.id }}" selected>{{ course }}</option>
                </select>
                <input type="text" name="name" maxlength="255" required id="id_name">
                <input type="file" name="slide" id="id_slide">
                <input type="url" name="video" id="id_video">
                <textarea name="notes" cols="40" rows="10" id="id_notes"></textarea>
            </div>
            <button type="submit" ><a href="{% url 'course_overview' course.id %}">Cancel</a></button>
            <button type="submit" name="add_lecture">Add lecture</button>
        </div>
    </div>
</form>
{% endif %}
{% endblock %}

lms/templates/courses/add_teacher.html
{% extends "../lms/index1.html" %}
{% block title %}Add Teacher{% endblock %}

{% block content %}
{% if form %}
<form method="POST">
    {% csrf_token %}
    <div class="box-bg-create-course">
        <div class="box-create-course">
            <h1>Add teacher to this course</h1>
            <div class="label-fields-profile">
                <label for="id_course">Teacher</label>
                <label for="id_name">Course</label>
            </div>

            <div class="inp-fields-profile" >
                <select name="teacher" required id="id_teacher">
                    {% for teacher in other_teachers %}
                        <option value="{{ teacher.id }}" selected>{{ teacher }}</option>
                    {% endfor %}
                </select>
                <select name="course" required id="id_course">
                    <option value="{{ course.id }}" selected>{{ course }}</option>
                </select>
            </div>
            <button type="submit">Save changes</button>
        </div>
    </div>
</form>
{% endif %}
{% endblock %}

lms/templates/courses/add_unit.html
{% block title %}Create Unit{% endblock %}

{% block content %}
{% if unit_create_form %}
<form method="POST">
    {% csrf_token %}
    <div id="div_id_lecture" class="form-group">
        <label for="id_lecture" class=" requiredField">
            Lecture<span class="asteriskField">*</span></label>
        <div class=""><select name="lecture" class="select form-control" required id="id_lecture">
            <option value="{{ lecture.id }}" selected>{{ lecture }}</option></select></div>
    </div>
    <div id="div_id_name" class="form-group">
        <label for="id_name" class=" requiredField">
            Name<span class="asteriskField">*</span></label>
        <div class="">
            <input type="text" name="name" maxlength="255" class="textinput textInput form-control"
                required id="id_name"></div>
    </div>
    <div id="div_id_notes" class="form-group">
        <label for="id_notes" class="">Notes</label>
        <div class="">
            <textarea name="notes" cols="40" rows="10" class="textarea form-control" id="id_notes">
            </textarea></div>
    </div>
    <div id="div_id_slide" class="form-group"> <label for="id_slide" class="">Slide</label>
        <div class="">
            <input type="file" name="slide" class="clearablefileinput form-control-file"
                id="id_slide"></div>
    </div>
    <div id="div_id_video" class="form-group"> <label for="id_video" class="">Video</label>
        <div class=""><input type="url" name="video" maxlength="255" class="urlinput form-control"
                id="id_video"></div>
    </div>
    <div id="div_id_reading" class="form-group"> <label for="id_reading" class="">Reading</label>
        <div class=""> <input type="text" name="reading" maxlength="255"
                class="textinput textInput form-control" id="id_reading"></div>
    </div>

    <button type="submit" name="add_unit">Add</button>
</form>
{% endif %}
{% endblock %}

lms/templates/courses/course_detail.html
<div class="box-main-das">
    <div class="box-main-control">
        <div class="box-iteam-control">
            <h1>Menu</h1>
            <ul>
                {% if can_modify_obj %}
                    <li id="modify-course">
                        <a href="{% url 'modify_course' course.id %}" name='unitoflecture'>Modify course</a>
                    </li>
                    <li>
                        <a href="{% url 'add_lecture' course_id=course.id %}" name='unitoflecture'>Add lecture</a>
                    </li>
                {% endif %}

                <li class="item">Teacher
                    <ul class="itemshow" >
                        {% if detail.teachers %}
                            {% for teacher in detail.teachers %}
                                <li><a href="{% url 'user_profile' teacher.id %}" >{{ teacher.name }}</a></li>
                            {% endfor %}
                        {% endif %}
                        {% if can_modify_obj %}
                            <li><a href="{% url 'add_teacher' course.id %}">Add Teacher</a></li>
                        {% endif %}
                    </ul>
                </li>

                <li class="item">Classmate
                    <ul class="itemshow" >
                        {% if detail.classmates %}
                            {% for classmate in detail.classmates %}
                                {% if classmate != this_user %}
                                    <li>
                                        <a href="{% url 'user_profile' classmate.id %}" >{{ classmate.name }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </ul>
                </li>
                <li class="item">My course
                    <ul class="itemshow">
                        {% if my_courses %}
                            {% for course in my_courses %}
                                <li>
                                    <a href="{% url 'course_overview' course.id %}"><i>{{ course.name }}</i></a>
                                </li>
                            {% endfor %}
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>

    {% if detail %}
        {% if detail.lectures %}
            <div class="box-main-content">
                <h1> {{ course.name }} </h1>
                {% for lecture in detail.lectures %}
                    {% if lecture.lecture %}
                        {% with lect=lecture.lecture %}
                            <div class="box-das-content-details">
                                <div class="das-content">
                                    <div class="das-content-title">
                                        <i class="fab fa-elementor"></i>
                                        <h1>{{ lect }}</h1>
                                    </div>
                                    <div class="das-content-show">
                                        {% if lect.notes %}
                                            <p>{{ lect.notes }}</p>    
                                        {% endif %}

                                        {% if lect.video %}
                                            <a href="{{ lect.video }}"> <i> This is video </i></a> 
                                        {% endif %}

                                        {% if lect.slide %}
                                            <a href="{% url 'view_file' lect.slide.path %}"> <i>  {{ lect.get_slide_name }} </i></a>
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="btn-modifly">
                                    {% if can_modify_obj %}

                                        <form action="{% url 'delete_lect' lect.id %}" method="POST">
                                            {% csrf_token %}
                                            <input type="submit" id="btndelete" onclick="return confirm('Are you sure to delete?')" value="Delete">
                                        </form>

                                        <form action="{% url 'modify_lect' course.id lect.id %}" method="GET">
                                            {% csrf_token %}
                                            <button type="submit" name="save-changes" id="btnchange">Modify</button>
                                        </form>

                                    {% endif %}
                                </div>
                            </div>
                        {% endwith %}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
    {% endif %}
</div>

lms/templates/courses/course_overview.html
{% extends "../lms/index1.html" %}
{% block title %} {{ course.id }} {{ course.name }} {% endblock%}

{% block content %}
    {% if not enrolled %}
    <div class="bg-view">
        <div class="view-course">
            <div class="show-name-course">
                <h1> {{ course.name }} </h1>
            </div>
            
                {% if teaches %}
                    {% for teach in teaches %}
                    <div class="show-teacher-course">
                        <div class="img-teacher-course">
                            <img src="{{ teach.teacher.image.url }}" alt="image teacher">
                        </div>
                        <div class="name-teacher-course">
                            <a href="{% url 'user_profile' teach.teacher.id %}"> {{ teach.teacher.name }} </a>
                        </div>
                    </div>
                    {% endfor %}
                {% endif %}
            

            {% if not can_modify_obj %}
                <div class="btn-enroll">
                    <a href="{% url 'enroll' course.id %}">Enroll</a>
                    <p>Enroll to become one of the members in this course</p>
                </div>
            {% endif %}
            
        </div>
        <div class="course-descript">
            <h1>About this course</h1>
            <i> {{ course.description }} </i>
        </div>
    </div>              
    {% else %}
        {% include 'courses/course_detail.html' %}
        <script>
            var div_overview = document.getElementById("if-enrolled");
            div_overview.style.display = "none";
        </script>
    {% endif %}
{% endblock %}

lms/templates/courses/create.html
{% extends '../lms/index1.html' %}
{% block title %}Create Course{% endblock %}

{% block content %}
<form method="POST" enctype='Multipart/form-data'>
    {% csrf_token %}
    <div class="box-bg-create-course">
        <div class="box-create-course">
            <h1>Create a new course</h1>
            <div class="label-fields-profile" >
                <label for="">image course</label>
                <label for="">name course</label>
                <label for="">descriptions course</label>
            </div>

            <div class="inp-fields-profile" >
                <input type="file" name="image" accept="image/*" >
                <input type="text" name="name" maxlength="255" placeholder="Name course" required="" id="id_name">
                <textarea name="description" cols="40" rows="10" maxlength="10000" id="id_description"></textarea>
            </div>
            <button type="submit">Create</button>       
        </div>
    </div>
</form>
{% endblock %}

lms/templates/courses/dashboard.html
{% extends "../lms/index1.html" %}
{% load static %}
{% block title %} Dashboard {% endblock %}
{% block content %}

<!-- chi co giao vien ms hien doan nay len -->
    {% if this_teacher %}  
        <div class="c-box-course">
            <div class="img-course">
                <a href="{% url 'create_course' %}"><img src="{% static 'images/plus.png' %}" alt="Anh dau cong"></a>
            </div>
        </div>
    {% endif %}

    {% if my_courses %}
        {% for course in my_courses %}
            <div class="c-box-course">
                <div class="img-course">
                    {% if course.image %}
                        <img src="{{ course.image.url }}">
                    {% endif %}
                </div>
                
                <div class="name-course">
                    <i>{{ course.name }}</i>
                </div>
                
                <div class="bt-view">
                    <a href="../courses/{{ course.id }}/"><i>Details</i></a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>You are not enrolled in any courses!</p>
    {% endif %}

{% endblock %}

lms/templates/courses/enroll.html
{% extends '../lms/index1.html' %}
{% block title %}Enroll{% endblock %}

{% block content %}
    {% if already_enrolled %}
        <script>
            alert("You are already enrolled in this course!");
            window.location.href = "{% url 'course_detail' course_id %}";
        </script>
    {% else %}
        <form method="POST">
            {% csrf_token %}
            {{ enrollment_form }}
            <button type="submit" id="enroll">Thêm</button>
        </form>
                
        <script>
            window.onload = function() { var button = document.getElementById("enroll"); button.form.submit(); };
            alert("Enrolled successfully!");
            window.setTimeout(function() { location.href = "{% url 'course_overview' course_id %}"; }, 3000);
        </script>
    {% endif %}
{% endblock %}

lms/templates/courses/modify_comps.html
{% extends "../lms/index1.html" %}
{% block title %} Modify lecture {% endblock %}
{% block content %}
    <form method="POST" enctype='Multipart/form-data'>
        {% csrf_token %}
        <div class="box-bg-create-course">
            <div class="box-create-course">
                <h1>Modify lecture</h1>
                <div class="label-fields-profile">
                    <label for="id_course">Course</label>
                    <label for="id_name">Name</label>
                    <label for="id_slide">Slide</label>
                    <label for="id_video">Video</label>
                    <label for="id_notes">Notes</label>
                </div>
    
                <div class="inp-fields-profile">
                    <select name="course" required id="id_course">
                        <option value="{{ course.id }}" selected>{{ course }}</option>
                    </select>
                    <input type="text" name="name" value="{{ lecture.name }}" maxlength="255" required id="id_name">

                    {% if lecture.slide %}
                        <input type="file" name="slide" id="id_slide" value="{{ lecture.slide }}">
                    {% else %}
                        <input type="file" name="slide" id="id_slide">
                    {% endif %}

                    {% if lecture.video %}
                        <input type="url" name="video" value="{{ lecture.video }}" id="id_video" >
                    {% else %}
                        <input type="url" name="video" id="id_video" >
                    {% endif %}   

                    <textarea name="notes" cols="40" rows="10" id="id_notes"> {{ lecture.notes }} </textarea>
                </div>
                <button type="submit" ><a href="{% url 'course_overview' course.id %}">Cancel</a></button>
                <button type="submit">Save changes</button>                     
            </div>
        </div>
    </form>
{% endblock %}

lms/templates/courses/modify_course.html
{% extends "../lms/index1.html" %}
{% block title %} Modify course {% endblock %}
{% block content %}
    <form method="POST" enctype='Multipart/form-data'>
        {% csrf_token %}
        <div class="box-bg-create-course">
            <div class="box-create-course">
                <h1>Modify course</h1>
                <div class="label-fields-profile">
                    <label for="id_image">Image</label>
                    <label for="id_name">Name</label>
                    <label for="id_description">Description</label>
                </div>
    
                <div class="inp-fields-profile">
                    {% if course.image %}
                        <input type="file" name="image" accept="image/*" id="id_image" value="{{ course.image }}">
                    {% else %}
                        <input type="file" name="image" accept="image/*" id="id_image">
                    {% endif %}

                    <input type="text" name="name" value="{{ course.name }}" maxlength="255" required id="id_name">
                    
                    {% if course.description %}
                        <textarea name="description" cols="40" rows="10" maxlength="10000" id="id_description">{{ course.description }}</textarea>
                    {% else %}
                        <textarea name="description" cols="40" rows="10" maxlength="10000" id="id_description"></textarea>
                    {% endif %}
                    
                </div>
                <button type="submit" ><a href="{% url 'course_overview' course.id %}">Cancel</a></button>
                <button type="submit">Save changes</button>
                <button type="submit"><a href="{% url 'delete_course' course.id %}" onclick="return confirm('Are you sure to delete this course?')">Delete</a></button>                     
            </div>
        </div>
    </form>
{% endblock %}

lms/templates/courses/modify_lect.html
{% extends "../lms/index1.html" %}
{% block title %} Modify lecture {% endblock %}
{% block content %}
    <form method="POST" enctype='Multipart/form-data'>
        {% csrf_token %}
        <div class="box-bg-create-course">
            <div class="box-create-course">
                <h1>Modify lecture</h1>
                <div class="label-fields-profile">
                    <label for="id_course">Course</label>
                    <label for="id_name">Name</label>
                    <label for="id_slide">Slide</label>
                    <label for="id_video">Video</label>
                    <label for="id_notes">Notes</label>
                </div>
    
                <div class="inp-fields-profile">
                    <select name="course" required id="id_course">
                        <option value="{{ course.id }}" selected>{{ course }}</option>
                    </select>
                    <input type="text" name="name" value="{{ lecture.name }}" maxlength="255" required id="id_name">

                    {% if lecture.slide %}
                        <input type="file" name="slide" id="id_slide" value="{{ lecture.slide }}">
                    {% else %}
                        <input type="file" name="slide" id="id_slide">
                    {% endif %}

                    {% if lecture.video %}
                        <input type="url" name="video" value="{{ lecture.video }}" id="id_video" >
                    {% else %}
                        <input type="url" name="video" id="id_video" >
                    {% endif %}   

                    <textarea name="notes" cols="40" rows="10" id="id_notes"> {{ lecture.notes }} </textarea>
                </div>
                <button type="submit" ><a href="{% url 'course_overview' course.id %}">Cancel</a></button>
                <button type="submit">Save changes</button>                     
            </div>
        </div>
    </form>
{% endblock %}

lms/templates/courses/my_courses.html
{% extends "../lms/index1.html" %}
{% block content %}
<body>
    <div class="my-courses">
        <h1>My courses</h1>
        {% if my_courses %}
            <ul>
                {% for course in my_courses %}
                    <li><a href="../../courses/{{ course.id }}/">{{ course.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>You are not enrolled in any courses!</p>
        {% endif %}
    </div>
</body>
{% endblock %}

lms/templates/courses/search_result.html
{% extends "../lms/index1.html" %}
{% block title %}Search result{% endblock %}
{% block content %}
    {% if filtered_courses %}
        {% for course in filtered_courses %}
            <div class="c-box-course">
                <div class="img-course">
                    {% if course.image %}
                        <img src="{{ course.image.url }}">
                    {% endif %}
                </div>
                
                <div class="name-course">
                    <i>{{ course.name }}</i>
                </div>
                
                <div class="bt-view">
                    <a href="../courses/{{ course.id }}/"><i>Details</i></a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <a>No result found:(</a>
    {% endif %}
{% endblock %}