lms/urls.py
import django
from lms.views import change_password
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/change_password/', views.change_password, name='change_password'),
    path('accounts/change_password_done/', views.change_password_done, name='change_password_done'),
    path('accounts/login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('accounts/register/', views.register, name='register'),
    path('accounts/register-as-teacher/', views.teacher_register, name='teacher_register'),
    path('accounts/register_done', views.register_done, name='register_done'),
    path('courses/add/', views.create_course, name='create_course'),
    path('courses/<int:course_id>/enroll/', views.course_enroll, name='enroll'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('courses/<int:course_id>/', views.course_overview, name='course_overview'),
    path('search/', views.search_result, name='search'),
    path('files/<str:file_path>', views.view_file, name='view_file'),
    path('<lect_id>/delete/', views.delete_lect, name='delete_lect'),
    path('courses/<int:course_id>/lectures/<lect_id>/modify/', views.modify_lect, name='modify_lect'),
    path('courses/<int:course_id>/add_lecture/', views.add_lecture, name='add_lecture'),
    path('courses/<int:course_id>/modify/', views.modify_course, name='modify_course'),
    path('courses/<int:course_id>/delete/', views.delete_course, name='delete_course'),
    path('courses/<int:course_id>/add_teacher/', views.add_teacher, name='add_teacher'),
    path('users/<int:user_id>', views.user_profile, name='user_profile'),
    path('db/', views.db_import, name='db_import'),
] + static('images', document_root=settings.IMAGE_DIR)

lms/forms.py
from django import forms
from django.contrib.admin import widgets
from django.contrib.auth.forms import UserCreationForm, ReadOnlyPasswordHashField
from django.contrib.auth.models import User
from django.contrib.admin.widgets import RelatedFieldWidgetWrapper
from django.forms.widgets import URLInput
from django.utils.translation import gettext_lazy as _
from .models import *


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', ]


class StudentInfoForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput, required=False)
    facebook = forms.URLField(widget=forms.URLInput, required=False)
    twitter = forms.URLField(widget=forms.URLInput, required=False)
    website = forms.URLField(widget=forms.URLInput, required=False)

    class Meta:
        model = Student
        fields = ['image', 'facebook', 'twitter', 'website', ]


class AddTeacherForm(forms.ModelForm):
    teacher = forms.ModelChoiceField(queryset=Teacher.objects.all())
    course = forms.ModelChoiceField(queryset=Course.objects.all())
    class Meta:
        model = Teach
        fields = ['teacher', 'course',]


'''class TeachForm(forms.ModelForm):
    teacher = forms.ModelChoiceField(queryset=Teacher.objects.all())
    course = forms.ModelChoiceField(queryset=Course.objects.all())

    class Meta:
        model = Teach
        fields = ['teacher', 'course',]'''


class TeacherInfoForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput, required=False, localize=True)
    facebook = forms.URLField(widget=forms.URLInput, required=False)
    twitter = forms.URLField(widget=forms.URLInput, required=False)
    website = forms.URLField(widget=forms.URLInput, required=False)

    class Meta:
        model = Teacher
        fields = ['image', 'facebook', 'twitter', 'website', ]


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        queryset = User.objects.filter(email=email)
        if queryset.exists():
            raise forms.ValidationError("Email existed")
        return email
    
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['name', ]


class TeacherRegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
    staff = forms.BooleanField(label='I agree to the Terms and Conditions.', initial=False)

    class Meta:
        model = User
        fields = ('email', 'password', 'password2', 'staff', )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        queryset = User.objects.filter(email=email)
        if queryset.exists():
            raise forms.ValidationError("Email existed")
        return email
    
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(TeacherRegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserAdminCreationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields, plus a repeated password.
    """
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class CourseCreateForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput, required=False)
    
    class Meta:
        model = Course
        fields = ['id', 'image', 'name', 'description', ]


class LectureCreateForm(forms.ModelForm):
    notes = forms.TextInput()
    slide = forms.FileField(widget=forms.FileInput, required=False)
    video = forms.URLField(widget=forms.URLInput, required=False)
    reading = forms.TextInput()

    class Meta:
        model = Lecture
        fields = ['course', 'name', 'notes', 'slide', 'video', 'reading', ]


class AssignmentCreateForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ['student', 'finished', ]


class EnrollmentForm(forms.ModelForm):
    class Meta:
        model = Enroll
        fields = ['student', 'course',]

lms/templates/lms/base.html
{% load static %}
<!DOCTYPE html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style-0.css' %}">
    {% block js %}{% endblock %}
        
</head>
<body>
    <div class="c-main-bg">
        <div class="content-main"></div>
    </div>
    {% block content %}{% endblock %}
</body>
</html>

lms/templates/lms/index.html
{% extends '../lms/index1.html' %}
{% block title %}Trang chủ{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h3>Chào mừng, {{ user.username }}</h3>
            <p><a href="{% url 'logout' %}">Đăng xuất</a></p>
                {% if latest_subject_list %}
                    <ul>
                        {% for subject in latest_subject_list %}
                            <li><a href="courses/{{ subject.id }}/">{{ subject.name }}</a></li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>Không có sẵn khóa học nào.</p>
                {% endif %}
            {% else %}
                <p>Bạn chưa đăng nhập.</p>
                <a href="{% url 'login' %}">Đăng nhập</a>
            {% endif %}
{% endblock %}

lms/templates/lms/index1.html
{% load static %}
<!DOCTYPE html>
<html lang="vi"> 
    <head>
        <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Home page{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style-0.css' %}">
        <script src="https://kit.fontawesome.com/fe59a62916.js"></script>
        <script src="{% static 'js/js.js' %}" type="text/javascript"></script>
    </head>

    <body>  <!-- phần đầu trang nơi tất cả các trang khác kế thừa nó -->
        {% if user.is_authenticated %}
            <div class="header">
                <div class="header-logo">
                    <h1>MOC</h1>
                </div>

                <div class="header-search">
                    <form method="GET" action="{% url 'search' %}" name="forsearch" onsubmit="return noempty()">
                        <input type="search" name="q" id="search" minlength="2" placeholder="Search...">
                        <button type="submit"><i class="fas fa-search"></i></button>
                    </form>
                </div>

                <div class="navbar">
                    <a href="{% url 'index' %}">Home</a>
                    <a href="https://www.facebook.com/thepql" target="_blank">Contact</a>
                    <a href="{% url 'dashboard' %}">My Courses</a>
                    <a href="{% url 'user_profile' this_user.id %}">Profile</a>
                </div>

                <div class="bt-join-out">
                    <div class="user-image">
                        {% if this_user.image %}
                            <img src="{{ this_user.image.url }}" alt="Here"> 
                        {% endif %}
                    </div>
                    <div class="user-name">
                        <div class="show-name">
                            <p id="nameshow">
                                {% if this_user %}
                                    {{ this_user.name }}
                                {% endif %}
                            </p>
                            <a href="{% url 'logout' %}" id="logout">
                                <p>
                                    Logout
                                </p>    
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
        <div class="header">
            <div class="header-logo">
            </div>

            <div class="header-search">
            </div>

            <div class="navbar">
                <a href="">Home</a>
                <a href="">Community</a>
                <a href="">Contact</a>
                <a href="">Event</a>
                <a href="">Blog</a>
                <a href="{% url 'login' %}">Login</a>
            </div>

            <div class="bt-join-out">
                <div class="user-name">
                    <div class="show-name">
                        <p id="nameshow"> Join for free </p>
                        <a href="{% url 'register' %}" id="logout">
                            <p> Join for free </p>    
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}

        {% block content %}

            {% if user.is_authenticated %}
                {% if latest_course_list %}
                    {% for course in latest_course_list %}
                        <div class="c-box-course">
                            <div class="img-course">
                                {% if course.image %}
                                    <img src="{{ course.image.url }}">
                                {% endif %}
                            </div>
                            
                            <div class="name-course">
                                <i>{{ course.name }}</i>
                            </div>
                            
                            <div class="bt-view">
                                <a href="courses/{{ course.id }}/">View course</a>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}

            {% else %}
                <div class="home-b1">
                    <div class="home-b1-inner">
                        <div class="content">
                            <h1>The World's Best Online Course</h1>
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, et!</p>
                        </div>
                        <div class="funfact">
                            <div>1,000+ Courses</div>
                            <div>10,000+ Learners</div>
                            <div>Across 20 countries</div>
                            <div>Diversity</div>
                            <div>Profession</div>
                            </div>
                     </div>
                </div>

            {% endif %}
        {% endblock %}

        <div class="c-bg-footer">
            <div class="c-box-footer">
                <div class="c-box-content-footer">
                    <div class="footer-content-head">
                        <h1>MOC</h1>
                        <h3>About US</h3>
                        <p>Our team consists of 5 members Thep, Long, Tan, Phuong, Duong. They are very handsome and beautiful.Backend is Long, 4 other members are frontend. We seek support from google, youtube, and some other online tutorial sites. Especially the Stack Overflow.</p>
                    </div>
        
                    <div class="footer-content">
                        <h2>Some features</h2>
                        <a href="#">View course</a>
                        <a href="#">Enroll course</a>
                        <a href="#">See your profile</a>
                        <a href="#">Some change profile</a>
                        <a href="#">Passwork reset</a>
                        <a href="#">Beautiful friendly design</a>        
                    </div>
        
                    <div class="footer-content">
                        <h2>Popular and varied courses</h2>
                        <a href="#">Python</a>
                        <a href="#">C++, C, C#,...</a>
                        <a href="#">Data mining</a>
                        <a href="#">Algorithm</a>
                        <a href="#">Religion and culture</a>
                        <a href="#">Evolutionary biology</a>
                        <a href="#">Astronomy</a>
                    </div>
        
                    <div class="footer-content">
                        <h2>Idea sponsor</h2>
                        <a href="#">Google professor</a>
                        <a href="#">Youtube professor</a>
                        <a href="#">Stack Overflow professor</a>
                        <a href="#">Some other site tutorial professor</a>
                    </div>
                </div>
            </div>
            
            <div class="footer-content-latest">
                <div class="footer-text-content">
                    <p>@UET webteam 2020 theplongphuongduongtan</p>
                </div>
                <div class="footer-icon-content">
                    <i class="fab fa-facebook-square"></i>
                    <i class="fab fa-instagram-square"></i>
                    <i class="fab fa-twitter-square"></i>
                    <i class="fab fa-github-square"></i>
                    <i class="fab fa-youtube-square"></i>                
                </div>
            </div>
        </div>
    </body>
</html>

lms/templates/lms/user_profile.html
{% extends "../lms/index1.html" %}
{% block title %} Profile {% endblock %}

{% block content %}
    <div class="box-bg-profile">
        <div class="box-main-profile">
            <div class="bg-avatar">
                <div class="avatar">
                    {% if this_student %}
                        {% if this_student.image %}
                            <img src="{{ this_student.image.url }}">
                        {% endif %}
                    {% elif this_teacher %}
                        {% if this_teacher.image %}
                            <img src="{{ this_teacher.image.url }}">
                        {% endif %}
                    {% endif %}
                </div>
            </div>

            <div class="box-info">
                <h1>Information </h1>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Blanditiis rem et laborum ab dolore assumenda!</p>

                <div class="label-fields-profile">
                    <label for="">User name</label>
                    <label for="">Email</label>
                    <label for="">Joindate</label>
                </div>

                <div class="inp-fields-profile">
                    {% if this_student %}
                        <input type="text" value="{{ this_student.name }}" readonly> 
                        <input type="text" value={{ this_student.email }} readonly>
                        <input type="text" value="{{ this_student.joindate }}" readonly>
                    {% elif this_teacher %}
                        <input type="text" value="{{ this_teacher.name }}" readonly> 
                        <input type="text" value={{ this_teacher.email }} readonly>
                        <input type="text" value="{{ this_teacher.joindate }}" readonly>   
                    {% endif %}
                </div>
            </div>

            <div class="box-info">
                <h1>contact</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi, officia doloribus saepe numquam officiis dolor.</p>
                <div class="label-fields-profile">
                    <label for="">facebook</label>
                    <label for="">twitter</label>
                    <label for="">website</label>
                </div>
                <div class="inp-fields-profile">
                    {% if this_student %}
                        <input type="url" value={{ this_student.facebook }} readonly>
                        <input type="url" value={{ this_student.twitter }} readonly>
                        <input type="url" value={{ this_student.website }} readonly>
                    {% elif this_teacher %}          
                        <input type="url" value={{ this_teacher.facebook }} readonly>
                        <input type="url" value={{ this_teacher.twitter }} readonly>
                        <input type="url" value={{ this_teacher.website }} readonly>
                    {% endif %}
                </div>
            </div>

            {% if this_user == this_student or this_user == this_teacher %}
                <div class="box-update">
                    <h1>Update</h1>
                    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Exercitationem dolorem illo dolor rem nostrum consequuntur.</p>
                {% if form %}
                    <form method="POST" enctype='Multipart/form-data'>
                        {% csrf_token %}
                        <div class="label-fields-profile">
                            <label for="">avatar</label>
                            <label for="">facebook</label>
                            <label for="">websites</label>
                            <label for="">twitter</label>
                        </div>
                        <div class="inp-fields-profile">
                            <input type="file" name="image" accept="image/*" id="filechoiseimage">
                            <input type="url" name="facebook" placeholder="facebook" id="id_facebook">
                            <input type="url" name="website" placeholder="website" id="id_website">
                            <input type="url" name="twitter" placeholder="twitter" id="id_twitter">
                        </div>
                        <div class="btn-comfirm">
                            <button type="submit"><i>Save profile</i></button>
                            <a href="{% url 'change_password' %}"> <i>Change password here</i> </a>
                        </div>
                    </form>
                </div>
        </div>
            {% endif %}  
                <script>
                    var info_text = document.getElementById("student-info-header-txt");
                    info_text.textContent = "My profile";
                </script>  
            {% endif %}      
    </div>
{% endblock %}